const List<String> egyptianUniversities = [
  'Canadian International College (CIC)',
  'American University in Cairo (AUC)',
  'Cairo University',
  'Ain Shams University',
  'GUC (German University in Cairo)',
  'British University in Egypt (BUE)',
  'Misr International University (MIU)',
  'October 6 University',
  'Modern Sciences and Arts University (MSA)',
  'Future University in Egypt (FUE)',
  'Helwan University',
  'Alexandria University',
  'Assiut University',
  'Mansoura University',
  'Zagazig University',
  'Tanta University',
  'Benha University',
  'Fayoum University',
  'Suez Canal University',
  'Minia University',
  'South Valley University',
  'Kafrelsheikh University',
  'Aswan University',
  'Damietta University',
  'Port Said University',
  'Matrouh University',
  'Al-Azhar University',
];
